// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MovieGuideApi.Models;
using System;

namespace MovieGuideApi.Migrations
{
    [DbContext(typeof(MovieGuideContext))]
    partial class MovieGuideContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("MovieGuideApi.Models.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("MovieGuideApi.Models.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("MovieGuideApi.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Eventid");

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.HasIndex("Eventid");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MovieGuideApi.Models.User", b =>
                {
                    b.HasOne("MovieGuideApi.Models.Event")
                        .WithMany("users")
                        .HasForeignKey("Eventid");
                });
#pragma warning restore 612, 618
        }
    }
}
